#!/bin/bash

export NO_GAIL=0
export NO_AT_BRIDGE=0

dbus-test-runner --dbus-config /usr/share/dbus-test-runner/session.conf --task path_to_test-gtk-label-client --task-name Client --task path_to_test-gtk-label-server --parameter ./dbusmenu-gtk/$1 --task-name Server --ignore-return


